---
test:
  workers:
    type: local
    number: 1
  rounds:
    - label: Create a Car. [fixed-load]
      txDuration: 30
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: fabcar/functions/createCar.js
    - label: Create Car [fixed-rate]
      txNumber: 1000
      rateControl:
        type: fixed-rate
        opts:
          tps: 40
      workload:
        module: fabcar/functions/createCar.js
    - label: Query a Car. [fixed-load]
      txDuration: 30
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: fabcar/functions/queryCar.js
        arguments:
          assets: 1000
    - label: Query Car [fixed-rate]
      description: Test description for the query performance of the deployed contract.
      txNumber: 2000
      rateControl:
        type: fixed-rate
        opts:
          tps: 220
      workload:
        module: fabcar/functions/queryCar.js
    - label: Query_Car_1 [fixed-load]
      txDuration: 30
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: fabcar/functions/queryCar.js
        arguments:
          assets: 1000
    - label: Create_Car_1 [fixed-load]
      txDuration: 30
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5
      workload:
        module: fabcar/functions/createCar.js